{% set data= load_setup_py_data() %}
package:
  name: "ts-ess-earthquake"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.3
    - ts-ess-common
    - ts-salobj
  source_files:
    - python
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-ess-common
    - ts-salobj
